version: '3.4'

services:
  vitubeservice:
    image: vitubeservice
    build:
      context: .
      target: vitube_api
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
